baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

theme = "emdash"

[[menu.main]]
    identifier = "home"
    name = "HOME"
    title = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    identifier = "posts"
    name = "ARTICLES"
    title = "Articles"
    url = "/posts/"
    weight = 2
